development:
  adapter: postgresql
  encoding: unicode
  database: red_feed_development
  username: developer
  password:
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: red_feed_development
  host: 127.0.0.1
  user: ritvvijparrikh
  password:
  port: 5432
  min_messages: warning